### ISSUE TITLE
Bad solve result

### ISSUE THREAD

**Issue by Dolu89** [akheron/cubejs#3]
Hi,

I have a problem to solve a cube.
If I use this scramble : `L R' B2 F R' B F2 U' B' R' B D' L D2 B2 U L B' L2 B' R2 L2 D2 L2 U B2 R' B F R2 U F'`
On Cube explorer and solvemycube.com, I got this facelet : `fluuufdfdlrrbrbbulbdfdflrdlbbubdlfufrflflrrudbddrbluru`

But in the nodejs script, I got : `URDFURRUDLDRDRFBDFBRFRFBBUDRLLUDLRFULDDBLFUBUFBBLBLLUF`

Because of this, I can't obtain the good solve.

Did I do something wrong in my code ?
`Cube.initSolver();`
`var cube = new Cube();`
`cube.move("L R' B2 F R' B F2 U' B' R' B D' L D2 B2 U L B' L2 B' R2 L2 D2 L2 U B2 R' B F R2 U F'");`
`console.log('facelet: ' + cube.asString());`
`console.log('Solve: ' + cube.solve());`

Thank you for your help

Best regards

**Comment by akheron** [comment]
There's probably a bug in `Cube.asString()`. It's a long time since I've touched the code that I don't immediately see what causes it.

**Comment by akheron** [comment]
It was a bug in Cube.move. Fixed, thanks for the report!

**Comment by Dolu89** [comment]
I will try it ! Thank you very much !
