### ISSUE TITLE
Using cube.js in NodeJS

### ISSUE THREAD

**Issue by Arm1stice** [akheron/cubejs#5]
I am unable to import cube.js into nodejs, as there seems to be a problem in how the constructor calls functions

![Stack trace](http://i.imgur.com/IdjfVrr.png)

**Comment by Arm1stice** [comment]
Only happens when you try to initialize the Cube with `new require('cube.js')()`. The error doesn't occur when you create a Cube with `cube = require('cube.js').random()`

**Comment by akheron** [comment]
The `new ... ()` operator has a higher precedence than a function call, so you need add parentheses to the require function call: `cube = new (require('cube.js'))()`
